{{ if gt (len (.Values.application).containers) 0 }}
{{- range $key, $value := (.Values.application).containers }}
{{ if ($value.environment).secrets }}
{{ if gt (len ($value.environment).secrets) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $.Values.application.name $value.name }}
  namespace: {{ $.Values.application.namespace }}
data:
  {{- range $env_key, $env_value := $value.environment.secrets }}
  {{ $env_key }}: {{ $env_value | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
