{{- if or (.Values.extensions).service (.Values.extensions).probe }}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.extensions.probe }}
  annotations:
    prometheus.io/probe: "true"
  {{- end }}
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.namespace }}
  labels:
    app: {{ .Values.application.name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      {{- if .Values.extensions.service }}
      targetPort: http
      {{- else }}
      targetPort: metrics
      {{- end }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.application.name }}
{{- end }}
